spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

account:
  number:
    batch:
      size: 10