spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

scheduler:
  interest:
    cron: "0 0 1 * * ?"

logging:
  level:
    root: info

account:
  number:
    min-free: 10
    batch-size: 5
  base-numbers:
    CHECKING: 6000000000000000
    SAVINGS: 5536000000000000
    CURRENCY: 7000000000000000
    DEBIT: 4200000000000000