spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      auto-commit: false
      schema: ${DATABASE_SCHEMA:account_service}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA:account_service}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DATABASE_SCHEMA:account_service}
    liquibase-schema: ${DATABASE_SCHEMA:account_service}

springdoc:
  swagger-ui:
    enabled:  ${SWAGGERUI_ENABLED:true}
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}

server:
  port: 8090

scheduler:
  interest:
    cron: "0 0 1 * * ?"

logging:
  level:
    root: info
    liquibase: info

account:
  security:
    admin-user-ids: ${ADMIN_USER_IDS:}
  number:
    min-free: 10
    batch-size: 5
    max-free: 100
  base-numbers:
    CHECKING: 6000000000000000
    SAVINGS: 5536000000000000
    CURRENCY: 7000000000000000
    DEBIT: 4200000000000000