spring:
  datasource:
    hikari:
      maxLifetime: 30000

  task:
    scheduling:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true

account:
  number:
    min-free: 10
    batch-size: 5
    max-free: 25
  base-numbers:
    CHECKING: 6000000000000000
    SAVINGS: 5536000000000000
    CURRENCY: 7000000000000000
    DEBIT: 4200000000000000