name: CI

on:
  pull_request:
    branches:
      - hippogriff-master-stream8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sleep 5
          docker info

      - name: Set Testcontainers env variables
        run: |
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "TESTCONTAINERS_CHECKS_DISABLE=true" >> $GITHUB_ENV
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Clean build
        run: ./gradlew clean

      - name: Run tests
        run: ./gradlew test --no-daemon